import React from "react";
import { FilePlus, UploadCloud, Linkedin, BadgeCheck } from "lucide-react";

const actions = [
  {
    icon: <FilePlus className="text-purple-500 w-6 h-6" />,
    title: "Create New Resume",
    desc: "Start fresh and build a professional resume generated by AI in minutes.",
    link: "/resume-builder",
  },
  {
    icon: <Linkedin className="text-blue-500 w-6 h-6" />,
    title: "Connect To Your Socials",
    desc: "Generate your resume using your Github Profile or upload your LinkedIn profile.",
    link: "/socials",
  },
  {
    icon: <UploadCloud className="text-pink-500 w-6 h-6" />,
    title: "Apply For Jobs",
    desc: "Find and apply to jobs that match your skills and interests.",
    link: "/jobs",
  },
  {
    icon: <BadgeCheck className="text-green-500 w-6 h-6" />,
    title: "Check Resume Score",
    desc: "See how your resume performs and what to improve.",
    link: "/resume-checker",
  },
];

const QuickActions = ({ darkMode }) => {
  return (
    <section className={`${darkMode ? "bg-[#0d0b22] text-white" : "bg-white text-[#18181b]"} py-14 px-6 md:px-10`}>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 max-w-7xl mx-auto">
        {actions.map((action, index) => (
          <a key={index} href={action.link} className="no-underline">
            <div
              className={`
                rounded-xl p-6 cursor-pointer
                shadow-[0_0_20px_rgba(59,130,246,0.2)]
                hover:shadow-[0_0_30px_rgba(59,130,246,0.5)]
                transition-all duration-300
                ${darkMode
                  ? "bg-[#1a1735] border border-[#29244a] hover:border-blue-500"
                  : "bg-gray-100 border border-gray-200 hover:border-blue-400"
                }
              `}
            >
              <div className="mb-4">{action.icon}</div>
              <h3 className="text-lg font-semibold mb-2">{action.title}</h3>
              <p className={`text-sm leading-snug ${darkMode ? "text-gray-400" : "text-gray-600"} min-h-[72px]`}>
                {action.desc}
              </p>
            </div>
          </a>
        ))}
      </div>
    </section>
  );
};

export default QuickActions;
